### ISSUE TITLE
Implement short.io

### ISSUE THREAD

**Issue by empeje** [kulkultech/ngecilin#1]
- [x] In the options page, user can set their default URL shortener provider e.g. TinyURL, BitLy, and Short.io (#21)
- [x] If the Short.io is chosen, the user should give their **API Key**. (#21)
- [x] Additionally, in the options menu, they can set their default domain that we can get from this [List Domain API](https://developers.short.io/docs/getting-a-list-of-domains) (#21)
- [ ] In the main pop-up we will have a select box to choose the domain in addition to the textbox for the URL we want to shorten.
- [x] When they click "shorten" we will use the Short.io API to shorten the domain. (#21)

**Comment by empeje** [comment]
Mas @yuliefas this will be our **priority** ya.

**Comment by wicaksana94** [comment]
> * In the options page, user can set their default URL shortener provider e.g. TinyURL, BitLy, and Short.io

Is this will added by user statically or dynamically?

**Comment by empeje** [comment]
I received a notification that @wicaksana94 is asking the following question:

![WhatsApp Image 2020-10-17 at 3 12 14 PM](https://user-images.githubusercontent.com/11813607/96331893-34f67e00-108b-11eb-9948-7b5cea66f3f6.jpeg)
> Is this will added by the user statically or dynamically?

@wicaksana94 could elaborate more on your question? Which part that you feel confused about?

**Comment by empeje** [comment]
mas @wicaksana94 if you want to take this, you can take parts that not already addressed in the #21

**Comment by wicaksana94** [comment]
Hy guys, do you try to build this project on Windows 10? I had little trouble on my own laptop (it's around "node -p") :

awica@DESKTOP-R9337DG MINGW64 /e/JS_LAB/ngecilin (master)
$ yarn build
yarn run v1.22.4
$ yarn clean && env VERSION=$(node -p "require('./package.json').version") npx webpack
$ rm -rf dist
env: ‘-p’: No such file or directory
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by wicaksana94** [comment]
> I received a notification that @wicaksana94 is asking the following question:
> 
> ![WhatsApp Image 2020-10-17 at 3 12 14 PM](https://user-images.githubusercontent.com/11813607/96331893-34f67e00-108b-11eb-9948-7b5cea66f3f6.jpeg)
> 
> > Is this will added by the user statically or dynamically?
> 
> @wicaksana94 could elaborate more on your question? Which part that you feel confused about?

It's just the user interface layout, but now it's cleared by this commit from yuli efa suryantoro ( f6495a8 - Feature/short io provider (#21) )

**Comment by empeje** [comment]
> Hy guys, do you try to build this project on Windows 10? I had little trouble on my own laptop (it's around "node -p") :
> 
> awica@DESKTOP-R9337DG MINGW64 /e/JS_LAB/ngecilin (master)
> $ yarn build
> yarn run v1.22.4
> $ yarn clean && env VERSION=$(node -p "require('./package.json').version") npx webpack
> $ rm -rf dist
> env: ‘-p’: No such file or directory
> error Command failed with exit code 127.
> info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

I think it is related to the node version, which node version you're using @wicaksana94?

**Comment by wicaksana94** [comment]
> > Hy guys, do you try to build this project on Windows 10? I had little trouble on my own laptop (it's around "node -p") :
> > awica@DESKTOP-R9337DG MINGW64 /e/JS_LAB/ngecilin (master)
> > $ yarn build
> > yarn run v1.22.4
> > $ yarn clean && env VERSION=$(node -p "require('./package.json').version") npx webpack
> > $ rm -rf dist
> > env: ‘-p’: No such file or directory
> > error Command failed with exit code 127.
> > info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
> 
> I think it is related to the node version, which node version you're using @wicaksana94?

My node version is 10.16.3

**Comment by wicaksana94** [comment]
> > Hy guys, do you try to build this project on Windows 10? I had little trouble on my own laptop (it's around "node -p") :
> > awica@DESKTOP-R9337DG MINGW64 /e/JS_LAB/ngecilin (master)
> > $ yarn build
> > yarn run v1.22.4
> > $ yarn clean && env VERSION=$(node -p "require('./package.json').version") npx webpack
> > $ rm -rf dist
> > env: ‘-p’: No such file or directory
> > error Command failed with exit code 127.
> > info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
> 
> I think it is related to the node version, which node version you're using @wicaksana94?
My node version is 10.16.3

**Comment by empeje** [comment]
Ah I think it is because the command using the `$()` is not working on windows, I guess we can create new build script for windows.

Technically the build should do the following
- Using version coming from package.json
- set the version to the environment variable
- run webpack

Could you create a new issue for this windows failed to build error?

Temporarily you can run `npx webpack` manually.

**Comment by wicaksana94** [comment]
Ok, I did. https://github.com/kulkultech/ngecilin/issues/24
